/**
 * Java Starter Kit API
 *
 * Contact: contact@rawz06.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AdminProfileDto } from '../model/models';
import { CreateUserRequestDto } from '../model/models';
import { DashboardDto } from '../model/models';
import { ErrorDto } from '../model/models';
import { MessageDto } from '../model/models';
import { UpdateUserRequestDto } from '../model/models';
import { UserDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AdminServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create a new user
     * 
     * @param createUserRequestDto 
     */
    createUser(createUserRequestDto: CreateUserRequestDto, extraHttpRequestParams?: any): Observable<UserDto>;

    /**
     * Delete user
     * 
     * @param id 
     */
    deleteUser(id: number, extraHttpRequestParams?: any): Observable<MessageDto>;

    /**
     * Get admin dashboard data
     * 
     */
    getAdminDashboard(extraHttpRequestParams?: any): Observable<DashboardDto>;

    /**
     * Get admin profile (legacy endpoint)
     * 
     */
    getAdminProfile(extraHttpRequestParams?: any): Observable<AdminProfileDto>;

    /**
     * Get all users
     * 
     */
    getAllUsers(extraHttpRequestParams?: any): Observable<Array<UserDto>>;

    /**
     * Get user by ID
     * 
     * @param id 
     */
    getUserById(id: number, extraHttpRequestParams?: any): Observable<UserDto>;

    /**
     * Update user
     * 
     * @param id 
     * @param updateUserRequestDto 
     */
    updateUser(id: number, updateUserRequestDto: UpdateUserRequestDto, extraHttpRequestParams?: any): Observable<UserDto>;

}
