/**
 * Java Starter Kit API
 *
 * Contact: contact@rawz06.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AdminProfileDto } from '../model/models';
import { DashboardDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AdminDashboardServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get admin dashboard data
     * 
     */
    getAdminDashboard(extraHttpRequestParams?: any): Observable<DashboardDto>;

    /**
     * Get admin profile (legacy endpoint)
     * 
     */
    getAdminProfile(extraHttpRequestParams?: any): Observable<AdminProfileDto>;

}
