export * from './adminDashboard.service';
import { AdminDashboardService } from './adminDashboard.service';
export * from './adminDashboard.serviceInterface';
export * from './adminUsers.service';
import { AdminUsersService } from './adminUsers.service';
export * from './adminUsers.serviceInterface';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './auth.serviceInterface';
export * from './batch.service';
import { BatchService } from './batch.service';
export * from './batch.serviceInterface';
export * from './public.service';
import { PublicService } from './public.service';
export * from './public.serviceInterface';
export * from './user.service';
import { UserService } from './user.service';
export * from './user.serviceInterface';
export const APIS = [AdminDashboardService, AdminUsersService, AuthService, BatchService, PublicService, UserService];
