/**
 * Java Starter Kit API
 *
 * Contact: contact@rawz06.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ErrorDto } from '../model/models';
import { LoginRequestDto } from '../model/models';
import { LoginResponseDto } from '../model/models';
import { UserDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get current authenticated user
     * 
     */
    getCurrentUser(extraHttpRequestParams?: any): Observable<UserDto>;

    /**
     * Login to the application
     * 
     * @param loginRequestDto 
     */
    login(loginRequestDto: LoginRequestDto, extraHttpRequestParams?: any): Observable<LoginResponseDto>;

}
