/**
 * Java Starter Kit API
 *
 * Contact: contact@rawz06.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { BatchJobDto } from '../model/models';
import { JobExecutionDetailsDto } from '../model/models';
import { JobExecutionDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface BatchServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get all batch jobs
     * 
     */
    getAllBatchJobs(extraHttpRequestParams?: any): Observable<Array<BatchJobDto>>;

    /**
     * Get job execution details
     * 
     * @param jobName 
     * @param executionId 
     */
    getJobExecutionDetails(jobName: string, executionId: number, extraHttpRequestParams?: any): Observable<JobExecutionDetailsDto>;

    /**
     * Get job executions
     * 
     * @param jobName 
     * @param page 
     * @param size 
     */
    getJobExecutions(jobName: string, page?: number, size?: number, extraHttpRequestParams?: any): Observable<Array<JobExecutionDto>>;

}
