/**
 * Java Starter Kit API
 *
 * Contact: contact@rawz06.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AppInfoDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PublicServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get public application information
     * 
     */
    getPublicInfo(extraHttpRequestParams?: any): Observable<AppInfoDto>;

}
