/**
 * Java Starter Kit API
 *
 * Contact: contact@rawz06.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ErrorDto } from '../model/models';
import { UpdateProfileRequestDto } from '../model/models';
import { UserProfileDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UserServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get user profile
     * 
     */
    getUserProfile(extraHttpRequestParams?: any): Observable<UserProfileDto>;

    /**
     * Update user profile
     * 
     * @param updateProfileRequestDto 
     */
    updateUserProfile(updateProfileRequestDto: UpdateProfileRequestDto, extraHttpRequestParams?: any): Observable<UserProfileDto>;

}
