/**
 * Java Starter Kit API
 *
 * Contact: contact@rawz06.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface JobExecutionDto { 
    id?: number;
    instanceId?: number;
    jobName?: string;
    status?: string;
    startTime?: string;
    endTime?: string;
    exitCode?: string;
    exitDescription?: string;
}

