/**
 * Java Starter Kit API
 *
 * Contact: contact@rawz06.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StepExecutionDto } from './stepExecutionDto';


export interface JobExecutionDetailsDto { 
    id?: number;
    jobName?: string;
    status?: string;
    startTime?: string;
    endTime?: string;
    exitCode?: string;
    exitDescription?: string;
    createTime?: string;
    lastUpdated?: string;
    steps?: Array<StepExecutionDto>;
}

