/**
 * Java Starter Kit API
 *
 * Contact: contact@rawz06.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StepExecutionDto { 
    stepName?: string;
    status?: string;
    readCount?: number;
    writeCount?: number;
    commitCount?: number;
    rollbackCount?: number;
    startTime?: string;
    endTime?: string;
}

