/**
 * Java Starter Kit API
 *
 * Contact: contact@rawz06.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateProfileRequestDto { 
    email?: string;
    firstName?: string;
    lastName?: string;
    currentPassword?: string;
    newPassword?: string;
}

