/**
 * Java Starter Kit API
 *
 * Contact: contact@rawz06.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateUserRequestDto { 
    login?: string;
    password?: string;
    email?: string;
    firstName?: string;
    lastName?: string;
    role?: UpdateUserRequestDtoRoleEnum;
    active?: boolean;
}
export enum UpdateUserRequestDtoRoleEnum {
    User = 'USER',
    Admin = 'ADMIN'
};



