/**
 * Java Starter Kit API
 *
 * Contact: contact@rawz06.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserDto { 
    id?: number;
    login?: string;
    email?: string;
    firstName?: string;
    lastName?: string;
    role?: UserDtoRoleEnum;
    active?: boolean;
    createdAt?: string;
}
export enum UserDtoRoleEnum {
    User = 'USER',
    Admin = 'ADMIN'
};



